### ISSUE TITLE
[TRACKING] Implement Step 1 (Deploy) of pipeline

### ISSUE THREAD

**Issue by rossf7** [cncf-tags/green-reviews-tooling#101]
# Overview

Implement Deploy step of the green review pipeline. Including triggering it when a new release is created. This will be followed by the Run and Report steps.

- Parent Issue https://github.com/cncf-tags/green-reviews-tooling/issues/83
- Proposal 1 has the design https://github.com/cncf-tags/green-reviews-tooling/blob/main/docs/proposals/proposal-001-trigger-and-deploy.md

## Implementation Tasks

- [x] Add release trigger https://github.com/cncf-tags/green-reviews-tooling/issues/98 @dipankardas011 
- [x] Implement deploy step https://github.com/cncf-tags/green-reviews-tooling/issues/99 @SFulpius 
- [x] Modify flux resources for Falco to support pipeline https://github.com/cncf-tags/green-reviews-tooling/issues/100 @rossf7 
- [x] Rename sub component to config https://github.com/cncf-tags/green-reviews-tooling/issues/110
