### ISSUE TITLE
[ACTION] Rename Sub Components to Configs

### ISSUE THREAD

**Issue by rossf7** [cncf-tags/green-reviews-tooling#110]
Part of [Proposal-001 - Trigger and Deploy GitHub Action workflow from an upstream CNCF project
](https://github.com/cncf-tags/green-reviews-tooling/blob/main/docs/proposals/proposal-001-trigger-and-deploy.md)

# Task Description

- In #102 we renamed project sub components to configs in [proposal 1](https://github.com/cncf-tags/green-reviews-tooling/blob/main/docs/proposals/proposal-001-trigger-and-deploy.md) to have clearer naming. More specifically, Falco has three different different drivers (ebpf, modern-ebpf, kmod) that are each a valid configuration of Falco, rather than subcomponents of Falco.
- This issue tracks implementing this renaming.
- New structure for projects.json

```
{
    "projects": [
        {
            "name": "falco",
            "organization": "falcosecurity",
            "configs": [
                "ebpf",
                "modern-ebpf",
                "kmod"
            ]
        }
    ]
}
```

## Tasks

- [ ] Rename `sub_components` to `configs` in [projects.json](https://github.com/cncf-tags/green-reviews-tooling/blob/main/projects/projects.json)
- [ ] Update the [project_trigger.sh](https://github.com/cncf-tags/green-reviews-tooling/blob/main/scripts/project-trigger.sh) to use the new JSON format
- [ ] Rename `cncf_project_sub` input to `config` in [benchmark-pipeline.sh](https://github.com/cncf-tags/green-reviews-tooling/blob/main/.github/workflows/benchmark-pipeline.yaml#L9)

**Comment by vallss** [comment]
Hi! I've been very interested in WG Green Reviews' work lately and would love to get involved. I think it would be a great starting point to get some more context on what you do. :smile:
