### ISSUE TITLE
[Manual] Deploy cluster components in development environment

### ISSUE THREAD

**Issue by nikimanoledaki** [cncf-tags/green-reviews-tooling#3]
This is to create a dev environment for the Green Reviews WG.

### Cluster Creation
- [x] Create dev cluster
- [ ] Share kubeconfig with other WG contributors to reuse the same clusters --> ping @rossf7 for kubeconfig

### Cluster Components
Manage cluster components:

### Phase 1: Base-level cluster components (MVP)
- [x] Cilium
- [x] Kepler
- [ ] Prometheus

### Phase 2: Gather idle metrics for Falco
- [ ] Falco

Note: Falco can be deployed by the WG contributors in this dev environment to ensure that it can run alongside Kepler without any issues. However, we aim to extract this so that CNCF Project maintainers are responsible for configuring the deployment of the CNCF Project itself.

### Phase 3: Gather load-test metrics
- [ ] Synthetic workload
- [ ] Load generation tool e.g. k6

## Documentation
- [ ] Document this process on the `green-reviews-tooling` repository & the design doc

**Comment by rossf7** [comment]
Adding myself

**Comment by AntonioDiTuri** [comment]
I am also up for this 👍🏽

**Comment by AntonioDiTuri** [comment]
I have a question here: can we involve the Falco guys to get Falco deployed manually in the cluster as a first step? We could just give them the kubeconfig and get started while we think more about the pipeline approach. What do you think?

**Comment by rossf7** [comment]
Could we start by asking the Falco team how they would recommend we do the install? Maybe we can install it rather than giving access to the cluster?

**Comment by nikimanoledaki** [comment]
Falco maintainers are in the process of creating a new repository (https://github.com/falcosecurity/cncf-green-review-testing) that will store everything needed from their side e.g. Falco deployment manifests,  synthetic workload deployment manifests, benchmark tests, etc. However, Falco maintainers have less availability until mid-December.

It would be better to go with a workaround until then!

**Comment by nikimanoledaki** [comment]
They might use Ansible but I'm not sure: https://github.com/falcosecurity/kernel-testing/blob/main/ansible-playbooks/roles/bootstrap/tasks/main.yml

**Comment by AntonioDiTuri** [comment]
Synthetic workload has been installed we choose https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/helm-chart#readme and we install it manually via helm, here there is a pull request for the 2-lines documentation on how to reproduce it

**Comment by AntonioDiTuri** [comment]
I think we can close this issue, we have developed manually almost everything except from Falco
