### ISSUE TITLE
[Tracking] Gather metrics for idle Falco

### ISSUE THREAD

**Issue by AntonioDiTuri** [cncf-tags/green-reviews-tooling#34]
We decided to do first gather Falco idle metrics to validate our approach.
We gather metrics from k8s and kepler and we want to test those metrics for the falco project

## Metrics
- [x] deploy falco ( https://github.com/cncf-tags/green-reviews-tooling/pull/32 ) 
- [x] https://github.com/falcosecurity/cncf-green-review-testing/issues/11
- [x] collect and visualize metrics (https://github.com/cncf-tags/green-reviews-tooling/issues/20) 

Check that the data have been loaded and think about a way to export those metrics.
There is no need for fancy export for the moment a csv or similar simple format would be fine

## Benchmark test setup
- [x] https://github.com/cncf-tags/green-reviews-tooling/issues/50

**Comment by nikimanoledaki** [comment]
Requirements to consider:
- Provide a script to reproduce this test
- Set the duration of the idle test scenario to, for example, 15 minutes
- Track and export the results of the metrics in a consistent manner

**Comment by AntonioDiTuri** [comment]
Hey Niki! Thanks a lot for the proposals. 

My take is that we could opt for the same strategy we choose for the deployment of the infra-component. 
We could have a first step in which we have some simple bash script just to have a quick-and-dirty win and as soon as every component work we can design a well structured github workflow. 

What do you think?

**Comment by nikimanoledaki** [comment]
@AntonioDiTuri sounds good! I created this issue to track the setup for the first benchmark test (`idle`): https://github.com/cncf-tags/green-reviews-tooling/issues/50

+ added it to the description of this issue!

**Comment by nikimanoledaki** [comment]
Closing this issue as completed!
