### ISSUE TITLE
[Action] Upgrade Flux and use latest API versions for Flux resources

### ISSUE THREAD

**Issue by rossf7** [cncf-tags/green-reviews-tooling#54]
Currently we're using Flux 2.1.2 but the latest release is v2.2.3 https://github.com/fluxcd/flux2/releases/tag/v2.2.3

We should upgrade Flux and ensure we use the latest API versions.

## Tasks

- [ ] Upgrade to the latest Flux via updating tofu version var.   https://github.com/cncf-tags/green-reviews-tooling/blob/51ffcb27f534a62f13242f0297114a5c84259177/infrastructure/equinix-metal/variables.tf#L76
- [ ] Write docs for future upgrades
- [ ] Ensure Flux resources use latest version e.g  for HelmRelease upgrade from helm.toolkit.fluxcd.io/v2beta1 to v2beta2

**Comment by leonardpahlke** [comment]
I assume there are no issues to be expected since its a minor release, right.

**Comment by rossf7** [comment]
> I assume there are no issues to be expected since its a minor release, right.

Yes, no issues expected. Only complication is testing the change as the upgrade should be via tofu.
