### ISSUE TITLE
[Tracking] Bootstrap self-hosted GitHub Action runners

### ISSUE THREAD

**Issue by nikimanoledaki** [cncf-tags/green-reviews-tooling#58]
This issue tracks the configuration of GitHub Actions self-hosted runners with the Action Runners Controller (ARC) (see [step-by-step instructions](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/quickstart-for-actions-runner-controller)).

#### WG Green Reviews
_The following must be completed to create an idle test._
- [ ] Deploy ARC by adding Helm Chart via Flux
- [ ] [Authenticate to the GitHub API via ARC](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/authenticating-to-the-github-api)
- [ ] Configure a [runner scale set](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/quickstart-for-actions-runner-controller#configuring-a-runner-scale-set)

#### Falco Maintainers
_The following must be completed to create the first active test._
- [ ] Generate repository-level GitHub PAT https://github.com/falcosecurity/cncf-green-review-testing/issues/16
- [ ] Migrate any [load test](https://github.com/falcosecurity/cncf-green-review-testing/blob/main/kustomize/falco-driver/kmod/stress-ng.yaml) to a GitHub Actions workflow
- [ ] Store upstream GitHub PATs as Secrets
