### ISSUE TITLE
[TRACKING] release 0.2.0: Pipeline Automation of the Green Review for Falco

### ISSUE THREAD

**Issue by AntonioDiTuri** [cncf-tags/green-reviews-tooling#83]
# Intro
Hi everybody! We are back from KubeCon and after the Retro it is time to plan the next Quarter:

[During the meeting of the 10th April ](https://docs.google.com/document/d/19xUur8RjnNwO2rwLw5Wwf7ISQ9V41sr0UaartIJoQvE/edit#heading=h.ghikommsjh40) we outlined the priorities for the next Quarter. 

# Outcome
We will work on the Pipeline Automation of the Green Review for Falco.
The pipeline will have 3 steps in the scope 
1. Deploy - trigger GitHub Action workflow from an upstream release, including the binary
2. Run - run benchmark tests through GitHub Action
3. Report - fetch & store metrics

Other than the pipeline automation we will also work on a fourth proposal:

4. Benchmarking investigation - What is the best set of benchmarks to run for Cloud Native projects? 

This is one of the question that the investigation should answer, more details to follow in the tracking issue

We need a PR drafted for each of those proposal.

# Todo
For each proposal we will need to: 
- Create a TRACKING Issue 
- Work on the PR for detailing and structuring the proposal
- Review & Merge the PR

## Proposal 1 - Deploy

Leads: @rossf7 @dipankardas011 

- [X] Create an ACTION Issue for the proposal: https://github.com/cncf-tags/green-reviews-tooling/issues/84
- [X] [PR for detailing and structuring the proposal](https://github.com/cncf-tags/green-reviews-tooling/pull/88)
- [x] Review & Merge the PR
- [x] Tracking issue for implementation https://github.com/cncf-tags/green-reviews-tooling/issues/101

## Proposal 2 - Run 

Leads:  @nikimanoledaki  @locomundo

After deploying the Falco project, we need to run the benchmark tests.
This proposal assumes that the benchmarking are the one already defined [here](https://github.com/falcosecurity/cncf-green-review-testing/tree/main/kustomize/falco-driver/kmod). Look proposal 4 for better understanding why this is relevant.
Objective of this proposal is to document how to integrate the trigger of the benchmark in the GitHub Action

- [x] Create an ACTION Issue for the proposal: #86
- [x] PR for detailing and structuring the proposal
- [x] Review & Merge the PR
- [x] Tracking issue for implementation https://github.com/cncf-tags/green-reviews-tooling/issues/117

## Proposal 3 - Report

Leads: @AntonioDiTuri Chris Chinchilla

After deploying the project and running the benchmarking tests we need to collect the metrics.
At the moment we are just reading the [Kepler metrics through Prometheus](https://github.com/cncf-tags/green-reviews-tooling/blob/35af5a7ae1d5fadc4e2ec08dd578aa406fcbd91e/clusters/base/kepler-grafana.yaml#L112). We need a long term solution, we also need to discuss if we are intrested in saving lower level metrics (cpu,memory,etc.). 

- [x] Create a ACTION Issue for the proposal: https://github.com/cncf-tags/green-reviews-tooling/issues/95
- [x] PR for detailing and structuring the proposal
- [x] Review & Merge the PR
- [x] Set up a tracking issue for all the actions related to the proposal and sketch the single actions issues: https://github.com/cncf-tags/green-reviews-tooling/issues/145

-------

Posponed proposal since it has never kicked off, moving it to a separate ticket:

```
## Proposal 4 - Benchmarking investigation

Leads: TBD

While we work for the automation of the current solution for Falco we might also want to start the discussion of a standardized set of benchmarking tests we would like to run. It would be good to involve a benchmarking expert because we want to be sure to reproduce a meaningful scenario that reproduces meaningful metrics across different projects we will review
- [x] Create a ACTION Issue for the proposal: https://github.com/cncf-tags/green-reviews-tooling/issues/103
- [ ] PR for detailing and structuring the proposal
- [ ] Review & Merge the PR
- [ ] Set up a tracking issue for all the actions related to the proposal and sketch the single actions issues

If you want to get involved please drop a comment below 
```

https://github.com/cncf-tags/green-reviews-tooling/issues/144

**Comment by nikimanoledaki** [comment]
Perfect, thank you @AntonioDiTuri! 🎉 

PS: There might be relevant information that we can draw from the design doc (which has now been archived), especially from the section [2. Sustainability Assessment Pipeline](https://docs.google.com/document/d/19fzZW-IMv2kDNatKFHeHh7wqcEN0e2N60wzxvCGZd48/edit#heading=h.ac9w74nfgho) and on. Some of the info in the design doc has been refactored and moved to our docs but that was mostly for the infrastructure sections, not the pipeline sections.

**Comment by leonardpahlke** [comment]
> Are more in scope for Q3

Yes, agree. The other points are more important now (and we also need to have the automation in place to write documentaiton about it..) if we have time in Q2 that would be a good task otherwise Q3 material 👍 

> About the naming

+1

**Comment by AntonioDiTuri** [comment]
Switched me and niki on proposal 2 and 3. Added proposal 4. Clarified proposal 2

**Comment by rossf7** [comment]
Note for the `Report` proposal - the SRE metrics requested by the Falco team are listed here.
https://github.com/falcosecurity/cncf-green-review-testing/discussions/14#discussioncomment-8610132
