### ISSUE TITLE
[ACTION] Add release trigger

### ISSUE THREAD

**Issue by rossf7** [cncf-tags/green-reviews-tooling#98]
# Task Description

Implement trigger for a green review when there is a new release of a participating CNCF project. Falco is the first project.

Design is described in proposal 1.
https://github.com/cncf-tags/green-reviews-tooling/blob/main/docs/proposals/proposal-001-trigger-and-deploy.md#subscribing-to-releases

## Tasks

- [ ] Create GitHub Actions workflow for release trigger that runs weekly - [docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule)
- [ ] Add `clusters.yaml` with falco and sub components for drivers (`modern-ebpf`, `kmod`, `ebpf`) - [spec](https://github.com/cncf-tags/green-reviews-tooling/blob/main/docs/proposals/proposal-001-trigger-and-deploy.md#subscribing-to-releases)
- [ ] Check GitHub REST API for new releases - [spec](https://github.com/cncf-tags/green-reviews-tooling/blob/main/docs/proposals/proposal-001-trigger-and-deploy.md#subscribing-to-releases)
- [ ] Send workflow dispatch event to trigger pipeline workflow - [docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch)
- [ ] Save latest release per project to GitHub repository variable - [docs](https://docs.github.com/en/actions/learn-github-actions/variables)

**Comment by dipankardas011** [comment]
>  Check GitHub atom releases feed for new releases
wdyt?
https://github.com/ksctl/cli/blob/15f728468b4afaa6dcf17dcfcc6c4bc75a4e1762/scripts/install.sh#L22-L27

**Comment by rossf7** [comment]
@dipankardas011 Let's discuss in the meeting tomorrow. Does the latest release endpoint include pre-releases?

We may want to trigger the pipeline for those.
