### ISSUE TITLE
[ACTION] Implement deploy step of pipeline

### ISSUE THREAD

**Issue by rossf7** [cncf-tags/green-reviews-tooling#99]
# Task Description

Implement deploy step of green review pipeline. This is the first step of the pipeline and is followed by the benchmark and report steps.

Design is described in proposal 1. See trigger, deploy and cleanup sections.

https://github.com/cncf-tags/green-reviews-tooling/blob/main/docs/proposals/proposal-001-trigger-and-deploy.md#trigger

## Tasks

- [ ] Create GitHub Actions workflow that accepts inputs - [spec](https://github.com/cncf-tags/green-reviews-tooling/blob/main/docs/proposals/proposal-001-trigger-and-deploy.md#trigger)
- [ ] Identify manifests based on inputs and `kubectl apply -f`  - [spec](https://github.com/cncf-tags/green-reviews-tooling/blob/main/docs/proposals/proposal-001-trigger-and-deploy.md#deploy)
- [ ] Use `kubectl wait` to wait for flux to reconcile resources - [spec](https://github.com/cncf-tags/green-reviews-tooling/blob/main/docs/proposals/proposal-001-trigger-and-deploy.md#deploy)
- [ ] On success or error delete resources with `kubectl delete -f --wait` - [spec](https://github.com/cncf-tags/green-reviews-tooling/blob/main/docs/proposals/proposal-001-trigger-and-deploy.md#cleanup)
- [ ] Request fine grained GitHub PAT for triggering the workflow - [spec](https://github.com/cncf-tags/green-reviews-tooling/blob/main/docs/proposals/proposal-001-trigger-and-deploy.md#trigger)

**Comment by SFulpius** [comment]
I'm taking this issue.

**Comment by SFulpius** [comment]
One parameter of the workflow is the version parameter, which is defined as _Version of project to be tested_ in proposal 1. But what does it refers to exactly? To one git tag, to the image tag or something else?

**Comment by rossf7** [comment]
> One parameter of the workflow is the version parameter, which is defined as Version of project to be tested in proposal 1. But what does it refers to exactly? To one git tag, to the image tag or something else?

@SFulpius Good to clarify this. Its the git tag. For Falco we need it so we pull the correct image tag in the daemonset.
e.g. 0.38.0 is the latest release https://github.com/falcosecurity/falco/releases/tag/0.38.0

Something else that should probably be in the proposal and / or here is the implementation language for the workflow.

Our preference is to use bash whenever possible to have less dependencies. 

If this isn't possible or a higher level language is a better option then our preference is Go using the stdlib. As our team is most familiar with Go and its widely used within CNCF.

The steps here will mostly be using kubectl but I wanted to mention it and I'll add it to the agenda for next weeks meeting.
